### ISSUE TITLE
[Bug] Incorrect script/container behaviour that may result in broken installation/incompatible state

### ISSUE THREAD

**Issue by jiaz83** [jaymoulin/docker-jdownloader#134]
Whenever JDownloader is updating itself/Core, the main process is gone, while the helper installation process is applying the updates. The script currently doesn't properly wait for this process to finish, which then may result in incomplete installation of updates. In case of no or broken JDownloader.jar file, it is getting replaced by bundeled/old JDownloader.jar

Whenever the JDownloader.jar is replaced, it is important to also delete Core.jar file and the update directory.

Please feel free to get in contact with our support for further solution finding

1.) properly wait for updater process to finish
2.) update init script to also delete Core.jar file and update directory whenever JDownloader.jar file is replaced

**Comment by jiaz83** [comment]
Also see  #132

**Comment by pspzockerscene** [comment]
I may add that me and @jiaz83 are official JDownloader staff.

**Comment by kinslayer1982** [comment]
Honestly? I don't think that there is going to happen much about it here...

**Comment by jiaz83** [comment]
@kinslayer1982 but still important to notify about this issue as others might clone/continue this project

**Comment by jaymoulin** [comment]
> Honestly? I don't think that there is going to happen much about it here...

This project is not abandoned, but I'm the only one working on this project, nobody is helping me here. I'm always asking for support, tests, financial or reply and and I am always left alone. I have others priorities.

We already discussed about this issue with @jiaz83 few years ago and we couldn't find a reasonable solution as Jdownloader needs time in a ghost process to do some treatment. Docker does not allow that correctly. If I can remove the core.jar on error, this would not fix the problem about this ghost process and there is nothing I can do about it. 
So, yes, I'll do this rm core.jar, but please be respectful. If you want things to happen, at least do something about it instead of your irrespective bratty behaviour...

**Comment by jiaz83** [comment]
@jaymoulin Thank you for your help and work here! Another docker project for JDownloader *solved* the waiting by just waiting for all java processes to finish instead of waiting for specific pid. Maybe that'll work here as well?
You need to remove Core.jar and the update folder in case you replace JDownloader.jar, both are important.

**Comment by pspzockerscene** [comment]
> People like you are the main reason I don't want to code anymore

I feel this one! The only thing you can do is to ignore such comments and keep on going.

Back to topic:
The changes which jiaz means that were done in the other container project are these ones:
https://github.com/jlesage/docker-jdownloader-2/commit/6a8a6b44f367ec390f1f852febd3e39d7540c9d4

**Comment by kinslayer1982** [comment]
@jaymoulin Bratty behaviour? Eight - YES EIGHT! - months ago I reported this issue. I checked the things other people mentioned, I had a long discussion with jiaz about the reasons and possible solutions for this problem. I posted everything here to help with fixing it. And what did you do? NOTHING. No sign you cared, not even a single word to let people know that you are aware of it or that you haven't abandoned it.
But as soon as someone utters the suspicion that there's nothing happening here anymore you come out of your hole and start insulting people who are trying to help.
The only brat I see here is you. A****les like you are the reason I'm suffering from depression for almost 3 years now. You don't want code anymore? Great, do the world a favor and get off the net for good.

@pspzockerscene Yeah? Maybe his behaviour is the reason for comments like this.

**Comment by jaymoulin** [comment]
> @jaymoulin lYou don't want code anymore? Great, do the world a favor and get off the net for good.

That's what I did 4 years ago, hence the reason you didn't have any answer. You may have wanted to check closed issues and other documentations (first line of the project is "no more free support since 2021" for example). As this code is open source, anyone is able to propose help.
You're not happy with my code? It's up to you to clone/PR/edit ...

I just said you were irrespective and bratty.  I didn't insult anyone and didn't censor any of my words.

**Comment by jaymoulin** [comment]
> 
> Back to topic: The changes which jiaz means that were done in the other container project are these ones: [jlesage/docker-jdownloader-2@6a8a6b4](https://github.com/jlesage/docker-jdownloader-2/commit/6a8a6b44f367ec390f1f852febd3e39d7540c9d4)

This may be a good workaround if java is still a main process. This also may have an impact on performance. I (or anybody willing to PR) should be aware of that to contain this as possible
