### ISSUE TITLE
root owns files

### ISSUE THREAD

**Issue by peter233** [jaymoulin/docker-jdownloader#34]
hi
i have a odroid hc1 with omv 4.1.23-1
running the jaymoulin/jdownloader image in docker.
variables set on
PID = 100
GID = 1000
![Screenshot (4)](https://user-images.githubusercontent.com/34836355/62780252-8c778200-bab5-11e9-8254-acad8876945d.png)

But the downloadfile are owned by root.

have tried the extra argument -u 100:1000 the user then is unknown and have no permissions

**Comment by jaymoulin** [comment]
Looks like you created your container without the correct `-u` parameter which then created the download folder with root permissions.
You should :
- Change your download folders owner
- delete your actual container
- recreate it with `-u $(id -u)` parameter (`-u 100` in your case if you really are sure '100' is your user PID)

It will be owned by an unknown user inside your container but your host user will identify it correctly (it's due to the `/etc/passwd` file which is not shared between your container and your host. You can mount it as a volume if you want but this as no real purpose)

**Comment by peter233** [comment]
not working for me.
set the owner for the /sharedfolder to user1:users
created a new container with -u 100 and -u 100:1000 with a new downloadfolder
-> jdownloader says console missing seems jdownloader/docker? can not create the new downloadfolder
need help

**Comment by peter233** [comment]
but i think the problem is solved. i can delete files in my downloadfolder through my samba-share. no matter who the owner is now.
