### ISSUE TITLE
Jdownloader2 arm32 issues (probably permissions)

### ISSUE THREAD

**Issue by H34dl3ss** [jaymoulin/docker-jdownloader#38]
Hi,
I found your docker and pulled it onto my BananaPi.
First of all, thanks for sharing this! This is the only arm32 docker I found so far.

Here is my feedback:
I was a bit confused that [your docker](https://hub.docker.com/r/jaymoulin/jdownloader) is still named jdownloader and not jdownloader2.
It's also time consuming to find information which architecture the docker is build for - this seems to be a common issue as other dockers on docker hub also don't provide the information.
Anyway, after browsing your GitHub I saw the arm32 commits --> happy!

And finally, I have some issues to deal with.
The default download path given in your installation string is
`-v ~/Downloads:/root/Downloads`
But the docker container is set to use `/opt/JDownloader/Downloads`.
For some reason this cannot be changed via the MyJdownloader interface.

In general it seems, the container can't be modified.
I'm permanently getting update notifications but the version is not increasing.
Also, I can't install add-ons.
Most likely there are permission issues. I will edit this post to add my docker -run options later.
Maybe I can get a hand on some logs also - not sure where to find the right ones.
I'm not that familiar with docker when it comes to trouble shooting things so I appreciate any help!
Thanks in advance!

**Comment by jaymoulin** [comment]
Thanks you for your feedback and support. Your issue contains multiple ideas and questions so I'll try to be as clear as possible.

> I was a bit confused that [your docker](https://hub.docker.com/r/jaymoulin/jdownloader) is still named jdownloader and not jdownloader2.

Jdownloader is a deprecated product and jdownloader2 is now the latest maintained version. I tend to use name without version number in it as it could be confusing (you just had this confusion ;)) and prefer a product name which has a version number (my actual version number is 0.7.2 while writing https://github.com/jaymoulin/docker-jdownloader/releases)

> It's also time consuming to find information which architecture the docker is build for - this seems to be a common issue as other dockers on docker hub also don't provide the information.

Really few people build docker image for anything but amd64, which is why I made this. This image is built for all architectures which is clearly stated either in this repo description 
![image](https://user-images.githubusercontent.com/14236493/67862731-f6d31800-fb22-11e9-8969-27be95f4b484.png)
 or on hub docker
![image](https://user-images.githubusercontent.com/14236493/67862797-18340400-fb23-11e9-9b5f-c6b4e8755728.png)
But I know how difficult it could be to identify it's own architecture thus creating this multiarch image.

> And finally, I have some issues to deal with.
> The default download path given in your installation string is
> `-v ~/Downloads:/root/Downloads`
> But the docker container is set to use `/opt/JDownloader/Downloads`.
> For some reason this cannot be changed via the MyJdownloader interface.

You normally should be able to edit this via myjdownloader settings but here are some tricks you can do:
1. Remap your volume. Instead of `-v ~/Downloads:/root/Downloads` use `-v ~/Downloads:/opt/JDownloader/Downloads`
1. Add a download folder at download interface - You have a `chose another folder` link which allows you to add your path
![image](https://user-images.githubusercontent.com/14236493/67863303-f12a0200-fb23-11e9-807b-d12004058c3a.png)
1. Add the configuration volume (the `-v ~/jdownloader/cfg:/opt/JDownloader/cfg` part) - you'll have all jdownloader configuration files which will allow you to edit path. This last option may have impacts on all your other feedbacks.

> In general it seems, the container can't be modified.
> I'm permanently getting update notifications but the version is not increasing.

May be related to #32 but I can't do anything about this.

> Also, I can't install add-ons.

I don't add-on so I don't know how these should work but I'm pretty sure you could just add a volume from your add-on path to the docker container path

> Most likely there are permission issues. I will edit this post to add my docker -run options later.

I handle user permission correctly since many version, you have to pass the `-u <your_uid>` to use the user you need.

> Maybe I can get a hand on some logs also - not sure where to find the right ones.

99% of the logs are really verbose and jdownloader specific. I won't be able to help you for that, you should see with JDownloader support (https://support.jdownloader.org/)

If you find this product useful, please consider making donation to support me (sponsor button <3)

**Comment by H34dl3ss** [comment]
Well, here I am.
Started a new container without the -u option and all is nice now!
Updated are performing as well as installing extensions is no problem any more.
Thanks for your assistance. I'm gonna send you a coffe right away! :-)

**Comment by jaymoulin** [comment]
I'm glad your issue is now resolved.
Thanks you very much for your donation, this is really helping ❤️
