### ISSUE TITLE
Default download location such that no additional step is necessary

### ISSUE THREAD

**Issue by gr4nt3d** [jaymoulin/docker-jdownloader#47]
So apparently some things were changed and the old image I run was not showing in the web-UI anymore. With the new run-command it works flawlessly, though. Great docker image - Thank you very much!

However, once again I stumbled upon this:
> DON'T FORGET TO CHANGE YOUR DEFAULT DOWNLOAD FOLDER to `/Downloads`

Why not just leave the default download location as is ? And start with
```
~/Downloads:/opt/JDownloader/Downloads
```
instead of `-v ~/Downloads:/Downloads` as described #38 -> [answer](https://github.com/jaymoulin/docker-jdownloader/issues/38#issuecomment-547916972). The lines I suggest to list:

```sh
docker run -d --init --restart=always \
-v ~/Downloads:/opt/JDownloader/Downloads \
-v ~/jdownloader/cfg:/opt/JDownloader/cfg \
--name jdownloader \
-u $(id -u) \
-e MYJD_USER=email@email.com \
-e MYJD_PASSWORD=password \
jaymoulin/jdownloader
```
---

note: this is not an issue but rather a suggestion to change merely the `README.md`, but I don't know how to tag it correctly.

**Comment by jaymoulin** [comment]
Thank you for reporting this. If you find this product useful, please consider donation to help me continue maintain and create great products ([![Watch Ads](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/utip.png "Watch Ads")](https://utip.io/femtopixel) [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/femtopixel))

I did not want to put the download folder in the /opt/jdownloader forlder at the beginning due to isolation and permission problematic, but since everybody seems OK with this and suggesting this, I'm ok with it
