### ISSUE TITLE
Jdownloader with VPN (both in Docker containers)

### ISSUE THREAD

**Issue by FalconX14** [jaymoulin/docker-jdownloader#64]
This is not really an issue concerning your jdownloader image, this more a question concerning running jdownloader in combination with a vpn. I didn't know where to ask this, as it is not really a topic for the jdownloader forum and also not really a topic for your jdownloader docker image, but I thought you might know it or could help me anyway please :-)

I am running jdownloader and also a vpn container docker, both are working as they should. Jdownloader data goes through the vpn tunnel via "network" and the "vpn container (dynomitecentral/deluge-openvpn)". I have forwarded port 3129 in my router, but not in the docker image, as I get an error that it conflicts with the network mode.
The only problem I have: the Web UI/myjdownloader is damn slow, when it's acessed with VPN. Sometimes downloads are still loading, but the WebUI can't be accessed or Jdownloader can't be found.
Any hint, what I can do, to access the WebUI faster?
Can this be splitted somehow: WebUI < without VPN, Downloads < with VPN

**Comment by jaymoulin** [comment]
VPN are known to be slower than your own ISP as all your traffic is going through a third-party. You're describing an expected speed reduce and I don't think anything could be down to fast up this connection but I may be mistaking. 

As I don't use one nor know how you can configure your Docker container, I may not be able to help you on this one. If you can configure port forwarding inside your VPN container, you may be able to reroute everything going on port 3129 to a specified container without needing to expose it to your network. Something that may look like this
`Router port 3129 -> container vpn:3129 -> container jdownloader:3129`

I'm glad you find this product interesting and you may consider donation to help me continue maintain and create great products [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin)

**Comment by FalconX14** [comment]
The same port 3129 can't be used for two containers, I get an error when doing so.
But thanks your answer anyway.  Have a nice weekend.

**Comment by jaymoulin** [comment]
The trick is: don't expose port (no `-p 3129:3129` param nor `--network=host`) on your JDownloader container or you'll have a port conflict. If you really need the port to be exposed, use port-forwarding (`-p 8000:3129` for example).

Then, inside another container (such as your VPN one) you should be able to access your jdownloader container by its alias (depending on how you setup the container creation, they have to be in the same network) (e.g: `docker exec -it vpn ping jdownloader`).

A `docker-compose` example:

```
version: 2.7

services:
  jdownloader:
    image: jaymoulin/jdownloader
    restart: always
  vpn:
    image: dynomitecentral/deluge-openvpn
    restart: always
    ports:
      - "3129:3129"       
```
then I should be able to `docker-compose exec vpn ping jdownloader` 3129 port is open on host, forwaring in VPN container 3129, and inside jdownloader a 3129 port is also opened but not exposed to host. It could be accessed inside my `vpn` container using the `jdownloader` alias, as defined in my `docker-compose.yml` file.

For this to work, you must be sure 3129 is not already opened on you host machine. Otherwise, your `vpn` container would conflict with your host.

Once again, all of this depends on your own configuration but the port exposing / port forwarding remains. You can create as many container as you want with the same port as long as this said port is not conflicting on the host machine.

**Comment by FalconX14** [comment]
Forwarding the port 3219:3219 at the VPN container worked, indeed MyJdownloader WebUI is now faster, still slow, but more accessible.
Your hint with forwarding the port at the VPN container was very good!
Now I know how to access a WebUI of a container, which uses the network "container" mode (without this network mode/port conflicting error). Tried this with pyload, which works very good. WebUI is much faster in comparison to MyJdownloader. Maybe I change from Jdownloader to pyload, let's see...
Thanks again.

**Comment by jaymoulin** [comment]
Glad I was able to help. If you find this product useful, please consider donation to help me continue creating and maintaining.
